### ISSUE TITLE
Remove unnecessary files

### ISSUE THREAD

**Issue by walkerh** [BCM-HGSC/lims_reader#1]
If you want to keep them around:

1. Create a "`local`" directory inside your workspace (`lims_reader`).
2. Add "`/local`" to `~/.config/git/ignore`.
3. Copy the files you want to keep into `lims_reader/local`.
4. `git rm` the files.

**Comment by walkerh** [comment]
See my comments on your commits. You need to remove:

- __pycache__
- .gitignore~

You should then add __pycache__ to .gitignore.

**Comment by cssanchez23** [comment]
done

**Comment by walkerh** [comment]
Almost. I didn't realize that my dunder syntax would be interpreted as markdown.

    __pycache__ vs **pycache**

See 11d605f8d796bcab88e31eff0471ae3c4ae578be.

Do we still need `connect.py`?
